### ISSUE TITLE
ros2 humble

### ISSUE THREAD

**Issue by progrros** [mogar/spot_micro#1]
Hi, it is possible to create on ros humble? Can i contact you by email?

**Comment by mogar** [comment]
Yes, this works on humble. I'm actually developing/running on a docker container built around humble, so I don't have to mess with installation directly on the RPi. The docker stuff is in the `docker-full` directory, and should get you going with humble right away. You can also see general instructions for docker on an RPi robot over on [KevsRobots](https://www.kevsrobots.com/learn/learn_ros/04_docker_install.html).

Also this is very much a starter project. Doesn't do much now beyond manually move servos. You're welcome to use it, I just don't want to overpromise what's here.

Git comments are probably better if you want to talk about this project.

**Comment by progrros** [comment]
Thanks for your reply! I was able to start the another project from mike4192, but it written on ros1. I'm planning to launch spotmicro on a orange pi 5b due to better performance compared to RPi. Can you help rewrite some of your libraries? First I started write node to control it from the keyboard and in the future I would like to try to add simple CPG control

**Comment by mogar** [comment]
Orange Pi 5B looks cool. Did you get one with larger amounts of RAM?

This is just a hobby project for me to learn about motion control, so I'm mostly going to be focused on simple gait for the forseeable future.

Starting out by converting ROS nodes to ROS2 nodes (or vice versa) is a great way to learn about the system. There are some good [ROS2 tutorials here](https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html).  Between those and the KevsRobots instructions you should be able to figure out a lot.

**Comment by progrros** [comment]
Hi, yes I got orange with 16GB of RAM, also re-soldered PCA9685. Thank you for your help, if anything works out I'll post it. If you want to start some kind of common project, let me know.
